variables:
  DOCKERHUB_IMAGE: nekoimi/caddy:latest
stages:
  - build
  - push
build-job:
  stage: build
  only:
    - master
  tags:
    - docker
    - amd64
  script:
    - docker build -t $DOCKERHUB_IMAGE .
push-job:
  stage: push
  only:
    - master
  tags:
    - docker
    - amd64
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker push $DOCKERHUB_IMAGE
